# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generate images

on:
  push:
    branches: [ "main" ]    
    paths:
      - '**.py'
  pull_request:
    branches: [ "main" ]    
    paths:
      - '**.py'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup venv
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Get all changed python files
      id: changed-python-files
      uses: tj-actions/changed-files@v44
      with:
        # Avoid using single or double quotes for multiline patterns
        files: |
          **.py
    - name: List all changed files python files
      if: steps.changed-python-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-python-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - name: Generate images for all changed python files
      if: steps.changed-python-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-python-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          python $file
        done

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          **.png
        tag_name: "latest"
